#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
hwayeon_checkpoint04

@author: ganghwayeon
"""

import math
import matplotlib.pyplot as plt
import numpy as np
xpoints=[]
ypoints=[]

def logpower(voltage,current):
    ypoints.append(math.log(voltage*current))
    
r = input("type the name of the file: ")
f = open(r, "r")
count=0
with open(r, "r") as f:
    lines = f.readlines()
    for line in lines:
        line = line.split()
        if line[0].startswith("#"):
            FH = np.loadtxt(lines, delimiter=',', skiprows=3)
            xpoints.append(count)
            count=count+1
            val=line.split(',')
            logpower(float(val[0]),float(val[1]))
            print(xpoints)
        else:
            xpoints.append(count)
            count=count+1
            val=line.split(',')
            logpower(float(val[0]),float(val[1]))
            print(xpoints)

def main():
    fig = plt.figure()
    plt.plot(xpoints, ypoints)
    fig.suptitle('Voltage-Current Graph', fontsize=20)
    plt.xlabel('t', fontsize=18)
    plt.ylabel('p(t)', fontsize=16)
main()
