#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
hwayeon_checkpoint04

@author: ganghwayeon
"""

import math
import matplotlib.pyplot as plt
import numpy as np
xpoints=[]
ypoints=[]

def logpower(voltage,current):
    ypoints.append(math.log(voltage*current))
    
r = input("type the name of the file: ")
f = open(r, "r")
count=0
for x in f:
    li=x.strip()
    if not li.startswith("#"):
        xpoints.append(count)
        count=count+1
        val=x.split(',')
        logpower(float(val[0]),float(val[1]))

def main():
    fig = plt.figure()
    plt.plot(xpoints, ypoints)
    fig.suptitle('Voltage-Current Graph')
    plt.xlabel('t')
    plt.ylabel('p(t)')
main()
