#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@author: ganghwayeon
Checkpoint 2

"""
import math
def main():
    a = float(input("a: "))
    b = float(input("b: "))
    c = float(input("c: "))
    d = (b*b-4*a*c)
    
    if a != 0:
        if d > 0:                                       # two real roots
            r1 = (-1*b + d**(0.5))/(2*a)
            r2 = (-1*b - d**(0.5))/(2*a)

            print("Two Real roots are:")
            print("r1 =",r1)
            print("r2 =",r2)

        elif d < 0:                                     # two complex roots
            d *= -1
            real_part = -1*b/(2*a)
            img_part = (d**(0.5))/(2*a)
            
            print("Two Complex roots are:")
            print(format("r1 = {0} + {1}i").format(real_part, img_part))
            print(format("r1 = {0} - {1}i").format(real_part, img_part))
				
        else:                                           # single real root
            r = (-1*b)/(2*a)
            print("Single Real root, r =", r)
    else:
        r = -c/b
        print(r)
        
main()
